/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.platform.events.v1;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class FinancialTransactionEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8810506188959348648L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FinancialTransactionEvent\",\"namespace\":\"com.platform.events.v1\",\"fields\":[{\"name\":\"event_id\",\"type\":\"string\",\"doc\":\"Unique identifier for the event\"},{\"name\":\"transaction_id\",\"type\":\"string\",\"doc\":\"Domain-specific transaction ID\"},{\"name\":\"occurred_at\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},\"doc\":\"When the event occurred\"},{\"name\":\"amount_cents\",\"type\":\"long\",\"doc\":\"Transaction amount in cents\"},{\"name\":\"currency\",\"type\":\"string\",\"default\":\"USD\"},{\"name\":\"merchant_id\",\"type\":\"string\",\"doc\":\"Identifier for the merchant or pickup zone\"},{\"name\":\"payment_method\",\"type\":\"string\",\"doc\":\"e.g., Credit Card, Cash\"},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"TxnStatus\",\"symbols\":[\"PENDING\",\"SUCCESS\",\"FAILED\"]},\"doc\":\"Transaction status\"},{\"name\":\"region\",\"type\":\"string\",\"doc\":\"Deployment region (us-east, us-west)\"},{\"name\":\"trace_id\",\"type\":\"string\",\"doc\":\"Correlation ID for observability\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<FinancialTransactionEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<FinancialTransactionEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<FinancialTransactionEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<FinancialTransactionEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<FinancialTransactionEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this FinancialTransactionEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a FinancialTransactionEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a FinancialTransactionEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static FinancialTransactionEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Unique identifier for the event */
  private java.lang.CharSequence event_id;
  /** Domain-specific transaction ID */
  private java.lang.CharSequence transaction_id;
  /** When the event occurred */
  private java.time.Instant occurred_at;
  /** Transaction amount in cents */
  private long amount_cents;
  private java.lang.CharSequence currency;
  /** Identifier for the merchant or pickup zone */
  private java.lang.CharSequence merchant_id;
  /** e.g., Credit Card, Cash */
  private java.lang.CharSequence payment_method;
  /** Transaction status */
  private com.platform.events.v1.TxnStatus status;
  /** Deployment region (us-east, us-west) */
  private java.lang.CharSequence region;
  /** Correlation ID for observability */
  private java.lang.CharSequence trace_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FinancialTransactionEvent() {}

  /**
   * All-args constructor.
   * @param event_id Unique identifier for the event
   * @param transaction_id Domain-specific transaction ID
   * @param occurred_at When the event occurred
   * @param amount_cents Transaction amount in cents
   * @param currency The new value for currency
   * @param merchant_id Identifier for the merchant or pickup zone
   * @param payment_method e.g., Credit Card, Cash
   * @param status Transaction status
   * @param region Deployment region (us-east, us-west)
   * @param trace_id Correlation ID for observability
   */
  public FinancialTransactionEvent(java.lang.CharSequence event_id, java.lang.CharSequence transaction_id, java.time.Instant occurred_at, java.lang.Long amount_cents, java.lang.CharSequence currency, java.lang.CharSequence merchant_id, java.lang.CharSequence payment_method, com.platform.events.v1.TxnStatus status, java.lang.CharSequence region, java.lang.CharSequence trace_id) {
    this.event_id = event_id;
    this.transaction_id = transaction_id;
    this.occurred_at = occurred_at.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.amount_cents = amount_cents;
    this.currency = currency;
    this.merchant_id = merchant_id;
    this.payment_method = payment_method;
    this.status = status;
    this.region = region;
    this.trace_id = trace_id;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return event_id;
    case 1: return transaction_id;
    case 2: return occurred_at;
    case 3: return amount_cents;
    case 4: return currency;
    case 5: return merchant_id;
    case 6: return payment_method;
    case 7: return status;
    case 8: return region;
    case 9: return trace_id;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: event_id = (java.lang.CharSequence)value$; break;
    case 1: transaction_id = (java.lang.CharSequence)value$; break;
    case 2: occurred_at = (java.time.Instant)value$; break;
    case 3: amount_cents = (java.lang.Long)value$; break;
    case 4: currency = (java.lang.CharSequence)value$; break;
    case 5: merchant_id = (java.lang.CharSequence)value$; break;
    case 6: payment_method = (java.lang.CharSequence)value$; break;
    case 7: status = (com.platform.events.v1.TxnStatus)value$; break;
    case 8: region = (java.lang.CharSequence)value$; break;
    case 9: trace_id = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'event_id' field.
   * @return Unique identifier for the event
   */
  public java.lang.CharSequence getEventId() {
    return event_id;
  }


  /**
   * Sets the value of the 'event_id' field.
   * Unique identifier for the event
   * @param value the value to set.
   */
  public void setEventId(java.lang.CharSequence value) {
    this.event_id = value;
  }

  /**
   * Gets the value of the 'transaction_id' field.
   * @return Domain-specific transaction ID
   */
  public java.lang.CharSequence getTransactionId() {
    return transaction_id;
  }


  /**
   * Sets the value of the 'transaction_id' field.
   * Domain-specific transaction ID
   * @param value the value to set.
   */
  public void setTransactionId(java.lang.CharSequence value) {
    this.transaction_id = value;
  }

  /**
   * Gets the value of the 'occurred_at' field.
   * @return When the event occurred
   */
  public java.time.Instant getOccurredAt() {
    return occurred_at;
  }


  /**
   * Sets the value of the 'occurred_at' field.
   * When the event occurred
   * @param value the value to set.
   */
  public void setOccurredAt(java.time.Instant value) {
    this.occurred_at = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'amount_cents' field.
   * @return Transaction amount in cents
   */
  public long getAmountCents() {
    return amount_cents;
  }


  /**
   * Sets the value of the 'amount_cents' field.
   * Transaction amount in cents
   * @param value the value to set.
   */
  public void setAmountCents(long value) {
    this.amount_cents = value;
  }

  /**
   * Gets the value of the 'currency' field.
   * @return The value of the 'currency' field.
   */
  public java.lang.CharSequence getCurrency() {
    return currency;
  }


  /**
   * Sets the value of the 'currency' field.
   * @param value the value to set.
   */
  public void setCurrency(java.lang.CharSequence value) {
    this.currency = value;
  }

  /**
   * Gets the value of the 'merchant_id' field.
   * @return Identifier for the merchant or pickup zone
   */
  public java.lang.CharSequence getMerchantId() {
    return merchant_id;
  }


  /**
   * Sets the value of the 'merchant_id' field.
   * Identifier for the merchant or pickup zone
   * @param value the value to set.
   */
  public void setMerchantId(java.lang.CharSequence value) {
    this.merchant_id = value;
  }

  /**
   * Gets the value of the 'payment_method' field.
   * @return e.g., Credit Card, Cash
   */
  public java.lang.CharSequence getPaymentMethod() {
    return payment_method;
  }


  /**
   * Sets the value of the 'payment_method' field.
   * e.g., Credit Card, Cash
   * @param value the value to set.
   */
  public void setPaymentMethod(java.lang.CharSequence value) {
    this.payment_method = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return Transaction status
   */
  public com.platform.events.v1.TxnStatus getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * Transaction status
   * @param value the value to set.
   */
  public void setStatus(com.platform.events.v1.TxnStatus value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'region' field.
   * @return Deployment region (us-east, us-west)
   */
  public java.lang.CharSequence getRegion() {
    return region;
  }


  /**
   * Sets the value of the 'region' field.
   * Deployment region (us-east, us-west)
   * @param value the value to set.
   */
  public void setRegion(java.lang.CharSequence value) {
    this.region = value;
  }

  /**
   * Gets the value of the 'trace_id' field.
   * @return Correlation ID for observability
   */
  public java.lang.CharSequence getTraceId() {
    return trace_id;
  }


  /**
   * Sets the value of the 'trace_id' field.
   * Correlation ID for observability
   * @param value the value to set.
   */
  public void setTraceId(java.lang.CharSequence value) {
    this.trace_id = value;
  }

  /**
   * Creates a new FinancialTransactionEvent RecordBuilder.
   * @return A new FinancialTransactionEvent RecordBuilder
   */
  public static com.platform.events.v1.FinancialTransactionEvent.Builder newBuilder() {
    return new com.platform.events.v1.FinancialTransactionEvent.Builder();
  }

  /**
   * Creates a new FinancialTransactionEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FinancialTransactionEvent RecordBuilder
   */
  public static com.platform.events.v1.FinancialTransactionEvent.Builder newBuilder(com.platform.events.v1.FinancialTransactionEvent.Builder other) {
    if (other == null) {
      return new com.platform.events.v1.FinancialTransactionEvent.Builder();
    } else {
      return new com.platform.events.v1.FinancialTransactionEvent.Builder(other);
    }
  }

  /**
   * Creates a new FinancialTransactionEvent RecordBuilder by copying an existing FinancialTransactionEvent instance.
   * @param other The existing instance to copy.
   * @return A new FinancialTransactionEvent RecordBuilder
   */
  public static com.platform.events.v1.FinancialTransactionEvent.Builder newBuilder(com.platform.events.v1.FinancialTransactionEvent other) {
    if (other == null) {
      return new com.platform.events.v1.FinancialTransactionEvent.Builder();
    } else {
      return new com.platform.events.v1.FinancialTransactionEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for FinancialTransactionEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FinancialTransactionEvent>
    implements org.apache.avro.data.RecordBuilder<FinancialTransactionEvent> {

    /** Unique identifier for the event */
    private java.lang.CharSequence event_id;
    /** Domain-specific transaction ID */
    private java.lang.CharSequence transaction_id;
    /** When the event occurred */
    private java.time.Instant occurred_at;
    /** Transaction amount in cents */
    private long amount_cents;
    private java.lang.CharSequence currency;
    /** Identifier for the merchant or pickup zone */
    private java.lang.CharSequence merchant_id;
    /** e.g., Credit Card, Cash */
    private java.lang.CharSequence payment_method;
    /** Transaction status */
    private com.platform.events.v1.TxnStatus status;
    /** Deployment region (us-east, us-west) */
    private java.lang.CharSequence region;
    /** Correlation ID for observability */
    private java.lang.CharSequence trace_id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.platform.events.v1.FinancialTransactionEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.event_id)) {
        this.event_id = data().deepCopy(fields()[0].schema(), other.event_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.transaction_id)) {
        this.transaction_id = data().deepCopy(fields()[1].schema(), other.transaction_id);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.occurred_at)) {
        this.occurred_at = data().deepCopy(fields()[2].schema(), other.occurred_at);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.amount_cents)) {
        this.amount_cents = data().deepCopy(fields()[3].schema(), other.amount_cents);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.currency)) {
        this.currency = data().deepCopy(fields()[4].schema(), other.currency);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.merchant_id)) {
        this.merchant_id = data().deepCopy(fields()[5].schema(), other.merchant_id);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.payment_method)) {
        this.payment_method = data().deepCopy(fields()[6].schema(), other.payment_method);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.status)) {
        this.status = data().deepCopy(fields()[7].schema(), other.status);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.region)) {
        this.region = data().deepCopy(fields()[8].schema(), other.region);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.trace_id)) {
        this.trace_id = data().deepCopy(fields()[9].schema(), other.trace_id);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
    }

    /**
     * Creates a Builder by copying an existing FinancialTransactionEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.platform.events.v1.FinancialTransactionEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.event_id)) {
        this.event_id = data().deepCopy(fields()[0].schema(), other.event_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.transaction_id)) {
        this.transaction_id = data().deepCopy(fields()[1].schema(), other.transaction_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.occurred_at)) {
        this.occurred_at = data().deepCopy(fields()[2].schema(), other.occurred_at);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.amount_cents)) {
        this.amount_cents = data().deepCopy(fields()[3].schema(), other.amount_cents);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.currency)) {
        this.currency = data().deepCopy(fields()[4].schema(), other.currency);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.merchant_id)) {
        this.merchant_id = data().deepCopy(fields()[5].schema(), other.merchant_id);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.payment_method)) {
        this.payment_method = data().deepCopy(fields()[6].schema(), other.payment_method);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.status)) {
        this.status = data().deepCopy(fields()[7].schema(), other.status);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.region)) {
        this.region = data().deepCopy(fields()[8].schema(), other.region);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.trace_id)) {
        this.trace_id = data().deepCopy(fields()[9].schema(), other.trace_id);
        fieldSetFlags()[9] = true;
      }
    }

    /**
      * Gets the value of the 'event_id' field.
      * Unique identifier for the event
      * @return The value.
      */
    public java.lang.CharSequence getEventId() {
      return event_id;
    }


    /**
      * Sets the value of the 'event_id' field.
      * Unique identifier for the event
      * @param value The value of 'event_id'.
      * @return This builder.
      */
    public com.platform.events.v1.FinancialTransactionEvent.Builder setEventId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.event_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'event_id' field has been set.
      * Unique identifier for the event
      * @return True if the 'event_id' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'event_id' field.
      * Unique identifier for the event
      * @return This builder.
      */
    public com.platform.events.v1.FinancialTransactionEvent.Builder clearEventId() {
      event_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'transaction_id' field.
      * Domain-specific transaction ID
      * @return The value.
      */
    public java.lang.CharSequence getTransactionId() {
      return transaction_id;
    }


    /**
      * Sets the value of the 'transaction_id' field.
      * Domain-specific transaction ID
      * @param value The value of 'transaction_id'.
      * @return This builder.
      */
    public com.platform.events.v1.FinancialTransactionEvent.Builder setTransactionId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.transaction_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'transaction_id' field has been set.
      * Domain-specific transaction ID
      * @return True if the 'transaction_id' field has been set, false otherwise.
      */
    public boolean hasTransactionId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'transaction_id' field.
      * Domain-specific transaction ID
      * @return This builder.
      */
    public com.platform.events.v1.FinancialTransactionEvent.Builder clearTransactionId() {
      transaction_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'occurred_at' field.
      * When the event occurred
      * @return The value.
      */
    public java.time.Instant getOccurredAt() {
      return occurred_at;
    }


    /**
      * Sets the value of the 'occurred_at' field.
      * When the event occurred
      * @param value The value of 'occurred_at'.
      * @return This builder.
      */
    public com.platform.events.v1.FinancialTransactionEvent.Builder setOccurredAt(java.time.Instant value) {
      validate(fields()[2], value);
      this.occurred_at = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'occurred_at' field has been set.
      * When the event occurred
      * @return True if the 'occurred_at' field has been set, false otherwise.
      */
    public boolean hasOccurredAt() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'occurred_at' field.
      * When the event occurred
      * @return This builder.
      */
    public com.platform.events.v1.FinancialTransactionEvent.Builder clearOccurredAt() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'amount_cents' field.
      * Transaction amount in cents
      * @return The value.
      */
    public long getAmountCents() {
      return amount_cents;
    }


    /**
      * Sets the value of the 'amount_cents' field.
      * Transaction amount in cents
      * @param value The value of 'amount_cents'.
      * @return This builder.
      */
    public com.platform.events.v1.FinancialTransactionEvent.Builder setAmountCents(long value) {
      validate(fields()[3], value);
      this.amount_cents = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'amount_cents' field has been set.
      * Transaction amount in cents
      * @return True if the 'amount_cents' field has been set, false otherwise.
      */
    public boolean hasAmountCents() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'amount_cents' field.
      * Transaction amount in cents
      * @return This builder.
      */
    public com.platform.events.v1.FinancialTransactionEvent.Builder clearAmountCents() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'currency' field.
      * @return The value.
      */
    public java.lang.CharSequence getCurrency() {
      return currency;
    }


    /**
      * Sets the value of the 'currency' field.
      * @param value The value of 'currency'.
      * @return This builder.
      */
    public com.platform.events.v1.FinancialTransactionEvent.Builder setCurrency(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.currency = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'currency' field has been set.
      * @return True if the 'currency' field has been set, false otherwise.
      */
    public boolean hasCurrency() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'currency' field.
      * @return This builder.
      */
    public com.platform.events.v1.FinancialTransactionEvent.Builder clearCurrency() {
      currency = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'merchant_id' field.
      * Identifier for the merchant or pickup zone
      * @return The value.
      */
    public java.lang.CharSequence getMerchantId() {
      return merchant_id;
    }


    /**
      * Sets the value of the 'merchant_id' field.
      * Identifier for the merchant or pickup zone
      * @param value The value of 'merchant_id'.
      * @return This builder.
      */
    public com.platform.events.v1.FinancialTransactionEvent.Builder setMerchantId(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.merchant_id = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'merchant_id' field has been set.
      * Identifier for the merchant or pickup zone
      * @return True if the 'merchant_id' field has been set, false otherwise.
      */
    public boolean hasMerchantId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'merchant_id' field.
      * Identifier for the merchant or pickup zone
      * @return This builder.
      */
    public com.platform.events.v1.FinancialTransactionEvent.Builder clearMerchantId() {
      merchant_id = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'payment_method' field.
      * e.g., Credit Card, Cash
      * @return The value.
      */
    public java.lang.CharSequence getPaymentMethod() {
      return payment_method;
    }


    /**
      * Sets the value of the 'payment_method' field.
      * e.g., Credit Card, Cash
      * @param value The value of 'payment_method'.
      * @return This builder.
      */
    public com.platform.events.v1.FinancialTransactionEvent.Builder setPaymentMethod(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.payment_method = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'payment_method' field has been set.
      * e.g., Credit Card, Cash
      * @return True if the 'payment_method' field has been set, false otherwise.
      */
    public boolean hasPaymentMethod() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'payment_method' field.
      * e.g., Credit Card, Cash
      * @return This builder.
      */
    public com.platform.events.v1.FinancialTransactionEvent.Builder clearPaymentMethod() {
      payment_method = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * Transaction status
      * @return The value.
      */
    public com.platform.events.v1.TxnStatus getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * Transaction status
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.platform.events.v1.FinancialTransactionEvent.Builder setStatus(com.platform.events.v1.TxnStatus value) {
      validate(fields()[7], value);
      this.status = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * Transaction status
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'status' field.
      * Transaction status
      * @return This builder.
      */
    public com.platform.events.v1.FinancialTransactionEvent.Builder clearStatus() {
      status = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'region' field.
      * Deployment region (us-east, us-west)
      * @return The value.
      */
    public java.lang.CharSequence getRegion() {
      return region;
    }


    /**
      * Sets the value of the 'region' field.
      * Deployment region (us-east, us-west)
      * @param value The value of 'region'.
      * @return This builder.
      */
    public com.platform.events.v1.FinancialTransactionEvent.Builder setRegion(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.region = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'region' field has been set.
      * Deployment region (us-east, us-west)
      * @return True if the 'region' field has been set, false otherwise.
      */
    public boolean hasRegion() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'region' field.
      * Deployment region (us-east, us-west)
      * @return This builder.
      */
    public com.platform.events.v1.FinancialTransactionEvent.Builder clearRegion() {
      region = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'trace_id' field.
      * Correlation ID for observability
      * @return The value.
      */
    public java.lang.CharSequence getTraceId() {
      return trace_id;
    }


    /**
      * Sets the value of the 'trace_id' field.
      * Correlation ID for observability
      * @param value The value of 'trace_id'.
      * @return This builder.
      */
    public com.platform.events.v1.FinancialTransactionEvent.Builder setTraceId(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.trace_id = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'trace_id' field has been set.
      * Correlation ID for observability
      * @return True if the 'trace_id' field has been set, false otherwise.
      */
    public boolean hasTraceId() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'trace_id' field.
      * Correlation ID for observability
      * @return This builder.
      */
    public com.platform.events.v1.FinancialTransactionEvent.Builder clearTraceId() {
      trace_id = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public FinancialTransactionEvent build() {
      try {
        FinancialTransactionEvent record = new FinancialTransactionEvent();
        record.event_id = fieldSetFlags()[0] ? this.event_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.transaction_id = fieldSetFlags()[1] ? this.transaction_id : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.occurred_at = fieldSetFlags()[2] ? this.occurred_at : (java.time.Instant) defaultValue(fields()[2]);
        record.amount_cents = fieldSetFlags()[3] ? this.amount_cents : (java.lang.Long) defaultValue(fields()[3]);
        record.currency = fieldSetFlags()[4] ? this.currency : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.merchant_id = fieldSetFlags()[5] ? this.merchant_id : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.payment_method = fieldSetFlags()[6] ? this.payment_method : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.status = fieldSetFlags()[7] ? this.status : (com.platform.events.v1.TxnStatus) defaultValue(fields()[7]);
        record.region = fieldSetFlags()[8] ? this.region : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.trace_id = fieldSetFlags()[9] ? this.trace_id : (java.lang.CharSequence) defaultValue(fields()[9]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<FinancialTransactionEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<FinancialTransactionEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<FinancialTransactionEvent>
    READER$ = (org.apache.avro.io.DatumReader<FinancialTransactionEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










