/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.platform.events.v1;
@org.apache.avro.specific.AvroGenerated
public enum TxnStatus implements org.apache.avro.generic.GenericEnumSymbol<TxnStatus> {
  PENDING, SUCCESS, FAILED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TxnStatus\",\"namespace\":\"com.platform.events.v1\",\"symbols\":[\"PENDING\",\"SUCCESS\",\"FAILED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
