spring.application.name=producer
server.port=8083
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.transaction-id-prefix=txn-
spring.kafka.properties.schema.registry.url=http://localhost:8081
logging.level.com.platform.producer=INFO
